import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-4">
        <section className="flex">
          <div>
            <button className="btn">Start job</button>
          </div>
        </section>
      </main>
    </div>
  );
}
