import Head from "next/head";
import Jobs from "../components/jobs";
import Stats from "../components/stats";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-4">
        <Stats />
        <Jobs />
      </main>
    </div>
  );
}
