import Head from "next/head";
import Jobs from "../components/jobs";
import Stats from "../components/stats";
import Image from "next/image";
import Emissions from "../components/emissions.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-4">
        <div className="hero min-h-screen">
          <div className="hero-content text-center">
            <div className="max-w-md">
              <h1 className="text-5xl font-bold">Why eFlow?</h1>
              <p className="py-6">
                The impact businesses have on carbon emissions is far greater
                than that of any individual. We want to help YOU combat this.
              </p>
              <a
                href="https://www.rte-france.com/en/eco2mix/power-generation-energy-source"
                className="btn btn-primary"
              >
                Information Source
              </a>
              <p className="py-6"></p>
              <p className="py-6">
                Sources of US Greenhouse Gas Emissions in 2020
              </p>
              <Image
                src={Emissions}
                alt="Sources of US Greenhouse Gas Emissions in 2020"
                text-align="center"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
